name: PhantomControl
version: 1.0.3
main: jacobrosa.phantomcontrol.PhantomControl
author: KingBlueSapphire

commands:
  phantom:
    usage: /phantom <natural|forced> <true|false>
    description: Toggle phantom spawning
    permission: phantomcontrol.command.phantom
    aliases: [ phantoms ]